services:
  web:
    build: .
    container_name: it-dashboard-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # Dit slaat de /app/data map veilig op je Ubuntu server op
      - ./data:/app/data